apiVersion: v1
kind: Service
metadata:
  name: inventoryapi-service
  namespace: api
  labels:
    run: inventoryapi-service
spec:
  selector:
    app: frontend
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  type: NodePort
