apiVersion: v1
kind: Service
metadata:
  name: mysql8-service
  namespace: api
  labels:
    app: backend
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: backend
